/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for user settings configuration
 */
export interface UserSettings {
  /**
   * User interface language
   */
  language: "he" | "en";
  /**
   * User's registered degree identifier
   */
  degreeId?: string | null;
  /**
   * User's registered institution identifier
   */
  institutionId?: string | null;
  /**
   * User's registered degree title/name
   */
  degreeTitle?: string | null;
  /**
   * Preferred font family for UI
   */
  fontFamily?: string | null;
  /**
   * Whether to shuffle questions in quizzes
   */
  shuffleQuestions?: boolean;
  /**
   * Developer mode flag
   */
  devMode?: boolean;
}
